// @ts-check
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import boundaries from "eslint-plugin-boundaries";
import prettier from "eslint-config-prettier";
import globals from "globals";

export default tseslint.config(
  {
    // Paths that are never linted.
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/coverage/**",
      "**/*.tsbuildinfo",
      ".tools/**",
      // Auto-generated by Next.js and explicitly marked "should not be edited".
      "**/next-env.d.ts",
      // The secret-scan fixtures intentionally contain fake secrets and are
      // not real source code; they are exercised by gitleaks, not ESLint.
      "tools/secret-scan/fixtures/**",
      // Pinned Chromium browser bundle (provisioned locally / in CI).
      "packages/workflows/.chromium-cache/**",
      // Violation fixture for standing-rules-conformance.test.ts (linted ad hoc).
      "apps/web/__conformance-fixtures__/**",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  // Package-boundary enforcement: feature/app code may depend on the shared
  // packages, but nothing may reach around a package's public entry point and
  // shared packages may never import application code.
  {
    files: ["apps/**/*.{ts,tsx}", "packages/**/*.{ts,tsx}"],
    plugins: { boundaries },
    settings: {
      "boundaries/include": ["apps/**/*", "packages/**/*"],
      "boundaries/elements": [
        { type: "app", pattern: "apps/*", mode: "folder" },
        { type: "shared", pattern: "packages/*", mode: "folder" },
      ],
      "import/resolver": {
        typescript: {
          alwaysTryTypes: true,
          project: [
            "tsconfig.json",
            "apps/*/tsconfig.json",
            "packages/*/tsconfig.json",
          ],
        },
      },
    },
    rules: {
      // Cross-element dependency direction.
      "boundaries/element-types": [
        "error",
        {
          default: "disallow",
          rules: [
            { from: "app", allow: ["app", "shared"] },
            { from: "shared", allow: ["shared"] },
          ],
        },
      ],
      // Other elements may only be imported through their public entry point
      // (src/index.ts) — no reaching into package internals (e.g. the raw DB
      // client in @eqa/db is unreachable from outside the package).
      "boundaries/entry-point": [
        "error",
        {
          default: "disallow",
          rules: [{ target: ["app", "shared"], allow: "src/index.ts" }],
        },
      ],
    },
  },

  // Project-wide TypeScript hygiene.
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },

  // Config / tooling files run in Node and may use devDependencies freely.
  {
    files: [
      "**/*.config.{js,mjs,cjs,ts}",
      "vitest.config.ts",
      "packages/workflows/scripts/**/*.mjs",
    ],
    languageOptions: { globals: { ...globals.node } },
  },

  // Disables stylistic rules that conflict with Prettier. Must come last.
  prettier,
);
