import { randomUUID } from "node:crypto";
import { type EncryptedDataKey, type Kms, withDataKey } from "@eqa/crypto";
import {
  SHARED_SCHEMA,
  type TenantDescriptor,
  type TenantDirectory,
  tenantSchemaName,
} from "@eqa/tenant";
import { clientFor, type Database } from "./database";
import { TenantNotFoundError } from "./errors";
import { createTenantSchema } from "./migrate";
import type { Row } from "./sql-client";

const TENANTS = `${SHARED_SCHEMA}.tenants`;

export interface CreateTenantInput {
  readonly slug: string;
  readonly name: string;
}

interface TenantRow extends Row {
  id: string;
  slug: string;
  name: string;
  schema_name: string;
  status: string;
}

interface KeyRow extends Row {
  data_key_ciphertext: string;
  data_key_master_id: string;
}

function toDescriptor(row: TenantRow): TenantDescriptor {
  return {
    id: row.id,
    slug: row.slug,
    name: row.name,
    schemaName: row.schema_name,
    status: row.status === "suspended" ? "suspended" : "active",
  };
}

/**
 * The tenant registry, stored in the shared `platform` schema. Implements the
 * {@link TenantDirectory} port used by tenant resolution.
 *
 * On creation a per-tenant data key is generated by the KMS; only its encrypted
 * (wrapped) form is persisted. The plaintext data key is never stored, returned,
 * or logged — it is zeroed immediately after wrapping.
 */
export class TenantRegistry implements TenantDirectory {
  constructor(
    private readonly db: Database,
    private readonly kms: Kms,
  ) {}

  async findBySlug(slug: string): Promise<TenantDescriptor | null> {
    const { rows } = await clientFor(this.db).query<TenantRow>(
      `SELECT id, slug, name, schema_name, status FROM ${TENANTS} WHERE slug = $1`,
      [slug],
    );
    const row = rows[0];
    return row ? toDescriptor(row) : null;
  }

  async createTenant(input: CreateTenantInput): Promise<TenantDescriptor> {
    const schema = tenantSchemaName(input.slug);
    const id = randomUUID();

    const generated = await this.kms.generateDataKey();
    const wrapped = generated.encrypted;
    // We do not need the plaintext now; drop it from memory immediately.
    generated.plaintext.fill(0);

    await clientFor(this.db).query(
      `INSERT INTO ${TENANTS}
         (id, slug, name, schema_name, data_key_ciphertext, data_key_master_id, status)
       VALUES ($1, $2, $3, $4, $5, $6, 'active')`,
      [
        id,
        input.slug,
        input.name,
        schema,
        wrapped.ciphertext,
        wrapped.masterKeyId,
      ],
    );

    await createTenantSchema(this.db, schema);

    return {
      id,
      slug: input.slug,
      name: input.name,
      schemaName: schema,
      status: "active",
    };
  }

  /**
   * Returns the tenant's wrapped (encrypted) data key. This is safe to hand out:
   * it is ciphertext only and is useless without the KMS master key. Use it to
   * build a {@link TenantCipher} for application-level field encryption. The
   * plaintext data key is never exposed here.
   */
  async getEncryptedDataKey(slug: string): Promise<EncryptedDataKey> {
    const { rows } = await clientFor(this.db).query<KeyRow>(
      `SELECT data_key_ciphertext, data_key_master_id FROM ${TENANTS} WHERE slug = $1`,
      [slug],
    );
    const row = rows[0];
    if (!row) {
      throw new TenantNotFoundError(`No tenant with slug '${slug}'.`);
    }
    return {
      ciphertext: row.data_key_ciphertext,
      masterKeyId: row.data_key_master_id,
    };
  }

  /**
   * Loads the tenant's wrapped data key, unwraps it to a plaintext key held only
   * for the duration of `fn`, then zeroes it. The plaintext key never leaves
   * this scope.
   */
  async withTenantDataKey<T>(
    slug: string,
    fn: (dataKey: Buffer) => Promise<T> | T,
  ): Promise<T> {
    const { rows } = await clientFor(this.db).query<KeyRow>(
      `SELECT data_key_ciphertext, data_key_master_id FROM ${TENANTS} WHERE slug = $1`,
      [slug],
    );
    const row = rows[0];
    if (!row) {
      throw new TenantNotFoundError(`No tenant with slug '${slug}'.`);
    }
    const encrypted: EncryptedDataKey = {
      ciphertext: row.data_key_ciphertext,
      masterKeyId: row.data_key_master_id,
    };
    return withDataKey(this.kms, encrypted, fn);
  }
}
